# this file is *not* meant to cover or endorse the use of GitHub Actions, but rather to
# help test this project

name: ci

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11']
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install test dependencies
      run: python -m pip install -U tox
    - name: Test
      run: python -m tox -e py
    - name: Lint with flake8
      run: |
        flake8 --exit-zero --ignore=${{ env.flake8_ignore }} --max-complexity=${{ env.max_complexity }} --max-line-length=${{ env.max_line_length }} --exclude=.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg,nowcast --output-file=flake8.txt .

    - name: flake8 report
      uses: actions/upload-artifact@v3
      with:
        name: code-flake8
        path: flake8.txt
  
    - name: xunit report xml
      uses: actions/upload-artifact@v3
      with:
        name: xunit-report
        path: xunit-result.xml

    - name: coverage report xml
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage
        path: coverage.xml
